import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, User, GoogleAuthProvider, signInWithPopup } from 'firebase/auth';
import { getFirestore, collection, doc, query, where, getDocs, setDoc, updateDoc, onSnapshot, Timestamp, orderBy, limit } from 'firebase/firestore';
// @ts-ignore - Config is generated by set_up_firebase
import firebaseConfig from '../firebase-applet-config.json';

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export const auth = getAuth(app);
export const googleProvider = new GoogleAuthProvider();

// Types
export interface Student {
  id: string;
  name: string;
  fatherName: string;
  whatsappNumber: string;
  bFormNumber: string;
  imageUrl?: string;
  address: string;
  currentClass: string;
  registrationNumber: string;
  residentialStatus?: 'rihaishi' | 'gair-rihaishi';
  password: string;
  lastLesson?: string;
  dob?: string;
  teacherName?: string;
  admissionDate?: string;
  status: 'active' | 'graduated' | 'inactive';
  createdAt: any;
}

export interface DailyReport {
  id: string;
  studentId: string;
  date: any; // Can be string or Timestamp
  attendance: 'present' | 'absent' | 'leave';
  type: 'qaida' | 'quran';
  lesson: string;
  mistakes: string;
  description?: string;
  notes: string;
  teacherName?: string;
  updatedAt: any;
}

export interface Visitor {
  id: string;
  uid: string;
  email: string;
  displayName: string;
  photoURL: string;
  status: 'pending' | 'approved' | 'rejected';
  requestedAt: any;
  approvedAt?: any;
}

// Error handling helper
export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
    },
    operationType,
    path
  }
  console.error('Firestore Error: ', JSON.stringify(errInfo, null, 2));
  throw new Error(JSON.stringify(errInfo));
}
